# Generated by Django 2.1.5 on 2026-03-04 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientSupply',
            fields=[
                ('supply_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commodity', models.CharField(max_length=128)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_supplies', to='recipes.Recipe')),
            ],
            options={
                'verbose_name_plural': 'Ingredient Supplies',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('position', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='ingredientsupply',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_supplies', to='supply.Supplier'),
        ),
    ]
